services:
  db:
    build:
      context: DB
      dockerfile: Dockerfile
    image: mysql-db
    env_file:
      - .env
    ports:
      - "9001:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
