services:
  db:
    build:
      context: DB
      dockerfile: Dockerfile
    image: mysql-db
    env_file:
      - .env
    ports:
      - "9001:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uadmin", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./Frontend/management-category/
      dockerfile: DockerFile
    image: angular-frontend
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: springboot-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:

networks:
  app-network:
